name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  schedule:
    -
      cron: '30 0 * * *'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v3
      -
        name: 'Use Node.js 10.x'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      -
        name: 'Install Package'
        run: 'npm install --global stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'stargazed --username  "lokesh-coder" --token ${GITHUB_TOKEN} --repo "my-awesome-list" --message "stargazed update by GitHub Actions Workflow" --sort'
